# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.6.4
maven_group=io.github.thevoidblock
archives_base_name=headbrowser

# Dependencies
# https://modmuss50.me/fabric.html
fabric_api_version=0.154.2+26.1.2

# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.13.0+26.1

# https://linkie.shedaniel.dev/
modmenu_version=18.0.0

# https://mvnrepository.com/artifact/com.google.code.gson/gson
gson_version=2.14.0

# https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
okhttp_version=5.4.0

# https://mvnrepository.com/artifact/com.squareup.okio/okio
okio_version=3.17.0

# https://modrinth.com/mod/fabric-language-kotlin/versions
fabric_kotlin_version=1.13.13+kotlin.2.4.10
